MAX_GAME_LENGTH = 1000

RED_AIRPORT_ID = 30001
BLUE_AIRPORT_ID = 20001

AIR_PATROL_HEIGHT = 8000
A2G_PATROL_HEIGHT = 7000
AWACS_PATROL_HEIGHT = 7500
DISTURB_PATROL_HEIGHT = 8500


class SideType:
    RED = 'red'
    BLUE = 'blue'


class MissileType:
    A2G = '360'   # 空对地导弹，轰炸机配备
    A2A = '170'   # 空对空导弹，歼击机配备
    G2A = '170'   # 地对空导弹，地防配备
    S2A = '519'   # 舰对空导弹，护卫舰配备


class UnitType:
    A2A = 11
    A2G = 15
    AWACS = 12
    JAM = 13
    DISTURB = JAM
    UAV = 14
    SHIP = 21
    S2A = 31
    RADAR = 32
    COMMAND = 41
    AIRPORT = 71


class TeamStatus:
    NONE = 0
    MOVE_TO_POINT = 1
    MOVE_TO_LINE = 2
    MOVE_TO_AREA = 3
    TAKEOFF = 4
    LAND = 5
    AREA_PATROL = 6
    TAKEOFF_AREA_PATROL = 7
    LINE_PATROL = 8
    TAKEOFF_LINE_PATROL = 9
    AREA_HUNT = 10
    TAKEOFF_AREA_HUNT = 11
    TARGET_HUNT = 12
    TAKEOFF_TARGET_HUNT = 13
    PROTECT = 14
    TAKEOFF_PROTECT = 15
    AIR_ATTACK = 16
    RETURN_TO_BASE = 17
    TAKEOFF_MASS_SUCCESS = 18

    GROUND_ADD_TARGET = 30
    GROUND_REMOVE_TARGET = 31
    GROUND_RADAR_CONTROL = 32
    GROUND_SET_DIRECTION = 33
    GROUND_MOVE_DEPLOY = 34
    GROUND_DEPLOY = 35

    SHIP_MOVE_DEPLOY = 40
    SHIP_AREA_PATROL = 41
    SHIP_ADD_TARGET = 42
    SHIP_REMOVE_TARGET = 43
    SHIP_RADAR_CONTROL = 44

    AWACS_AREA_PATROL = 51
    AWACS_LINE_PATROL = 52
    AWACS_SET_MODE = 53
    AWACS_RADAR_CONTROL = 54
    AWACS_CANCEL_DETECT = 55

    DISTURB_AREA_PATROL = 60
    DISTURB_LINE_PATROL = 61
    DISTURB_SET = 62
    DISTURB_CLOSE = 63
    DISTURB_STOP = 64

    UAV_AREA_PATROL = 71
    UAV_LINE_PATROL = 72
    UAV_CANCEL_DETECT = 73

    RADAR_CONTROL = 81


class UnitStatus:
    NONE = 0
    DEAD = 1
    TAKEOFF = 2
    TAKEOFF_DONE = 3
    TAKEOFF_FAIL = 4
    LAND = 5
    LAND_DONE = 6
    LAND_FAIL = 7
    AIRPORT_WAIT = 8
    AIR_PATROL = 9
    AIR_POINT_PATROL = 10
    AIR_LINE_PATROL = 11
    AIR_AREA_PATROL = 12
    AIR_GUIDE = 13
    LINE_HUNT = 14
    AIR_ATTACK = 15
    RETURN_TO_BASE = 16
    AIR_ESCORT = 17

    GROUND_MOVING = 31
    GROUND_STOP = 32
    SHIP_PATROL = 41
    DISTURB_ON = 60
    DISTURB_OFF = 61
    RADAR_OFF = 90
    RADAR_ON = 91
    CANCEL_DETECT = 92


class MapInfo:
    X_MAX = Y_MAX = 175000
    X_MIN = Y_MIN = -175000
    Z_MAX = 12000
    Z_MIN = 0

    MOVE_UNIT_TYPES = [UnitType.A2A, UnitType.AWACS, UnitType.JAM, UnitType.UAV, UnitType.A2G,
                       UnitType.SHIP, UnitType.S2A, UnitType.RADAR, UnitType.COMMAND]
    SPEED_MAX = 500
    SPEED_MIN = 0
    COURSE_MAX = 360
    COURSE_MIN = 0
    PITCH_MAX = 180
    PITCH_MIN = -180
    ROLL_MAX = 180
    ROLL_MIN = -180

    DAMAGE_MAX = 100
    DAMAGE_MIN = 0
    FUEL_MAX = 10000  # TODO 乱写的
    FUEL_MIN = 0

    SIM_TIME_MAX = 9000  # 两小时
    SIM_TIME_MIN = 0

    A2A_NUM_MAX = 24
    A2G_NUM_MAX = 10
    AWACS_NUM_MAX = 1
    JAM_NUM_MAX = 3
    UAV_NUM_MAX = 3
    SHIP_NUM_MAX = 1
    GROUND_RADAR_NUM_MAX = 2
    GROUND_DEFENSE_NUM_MAX = 3
    COMMAND_POST_NUM_MAX = 2

    A2A_WEAPON_NUM_MAX = 6
    A2G_WEAPON_NUM_MAX = 2
    S2A_WEAPON_NUM_MAX = 36
    WAR_SHIP_WEAPON_NUM_MAX = 36
